# version: "3.7"

services:
  brick_ontology_tool:
    image: brick:dev
    command:  gunicorn -w 3 -b :8091 app:server
    ports:
      - 8091:8091
    depends_on:
      - redis

  celery: 
    image: brick:dev
    command: celery -A app.celery_app worker --loglevel=INFO
    depends_on:
      - brick_ontology_tool
      - redis


  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --port 6380
    ports: 
    - "6380:6380"
    volumes:
      - 'redis:/data'


volumes:
    redis: